export enum HeaderStyles {
  DEFAULT = "DEFAULT",
  SIMPLE_WITH_SUBTITLE = "SIMPLE_WITH_SUBTITLE",
  SIMPLE_LEFT_ALIGNED = "SIMPLE_LEFT_ALIGNED",
  CENTERED_DARK_BG = "CENTERED_DARK_BG",
  SIMPLE_WITH_BG_IMAGE = "SIMPLE_WITH_BG_IMAGE",
  WITH_CARDS = "WITH_CARDS",
}
