export enum TestimonialStyles {
  DEFAULT = "DEFAULT",
  IMAGE_RIGHT = "IMAGE_RIGHT",
  OVERLAP_IMAGE = "OVERLAP_IMAGE",
  IMAGE_BACKGROUND = "IMAGE_BACKGROUND",
  WITH_FEW_TESTIMONIALS = "WITH_FEW_TESTIMONIALS",
}
