export enum FeatureStyles {
  DEFAULT = "DEFAULT",
  IMAGE_ABOVE_LIST = "IMAGE_ABOVE_LIST",
  JUST_LIST = "JUST_LIST",
  TEXT_LEFT_FEATURE_RIGHT = "TEXT_LEFT_FEATURE_RIGHT",
  NO_ICONS = "NO_ICONS",
}
