export enum StatsStyles {
  DEFAULT = "DEFAULT",
  SIMPLE_DARK_BG = "SIMPLE_DARK_BG",
  WITH_TITLE_AND_DESCRIPTION = "WITH_TITLE_AND_DESCRIPTION",
  WITH_TITLE_AND_DESC_ON_DARK_BG = "WITH_TITLE_AND_DESC_ON_DARK_BG",
  WITH_TITLE_AND_DESC_IMAGE_BACKGROUND = "WITH_TITLE_AND_DESC_IMAGE_BACKGROUND",
  SPLIT_IMAGE_RIGHT = "SPLIT_IMAGE_RIGHT",
//   WITH_DESCRIPTION = "WITH_DESCRIPTION",
}
