export enum CTAStyles {
  DEFAULT = "DEFAULT",
  IMAGE_RIGHT_DARK_BG = "IMAGE_RIGHT_DARK_BG",
  SIMPLE_STACKED_CENTER_DARK_BG = "SIMPLE_STACKED_CENTER_DARK_BG",
  FULL_WIDTH_STACKED_CENTER_DARK_BG = "FULL_WIDTH_STACKED_CENTER_DARK_BG",
  IMAGE_LEFT_TEXT_RIGHT = "IMAGE_LEFT_TEXT_RIGHT",
  SIMPLE_STACKED_LEFT = "SIMPLE_STACKED_LEFT",
  SIMPLE_JUSTIFIED_BETWEEN = "SIMPLE_JUSTIFIED_BETWEEN",
}
